### ISSUE TITLE
have a problem running run.sh

### ISSUE THREAD

**Issue by heaij** [ralfkundel/p4-codel#9]
hello，When I run the run.sh script，An error occurs when loading instructions in the commandsCodelRouter.txt file to simple_switch，specifically these two instructions：'port_add r1-eth1 1  ；port_add r1-eth2 2'.  May I ask if you have encountered this problem？I really don't know what to do.  Any help is appreciated.
The specific error is as follows：
Running ['../behavioral-model/targets/simple_switch/sswitch_CLI', './router_compiled.json', '22222']
Using Thrift port 22222
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: Invalid device manager operation (ERROR)
RuntimeCmd: Invalid device manager operation (ERROR)

**Comment by ralfkundel** [comment]
did you solved the issue?

**Comment by heaij** [comment]
Not yet, I don't know where the problem is.
